# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Wandering Islander"
description: > # this means to ignore newlines until "email:"
   Bali bred - U.S raised - Developer trained

email: Komangwluce@gmail.mail
#blog logo
logo: "/MyBlog/assets/images/images.png"
# blog cover
cover: "/MyBlog/assets/images/bali.jpg"

name: 'Komang Luce'
author: 'Komang Luce'
author_image: "/MyBlog/assets/images/Author.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: "/MyBlog"

# social icons and sharing options
social:
  # - icon:	twitter
  #   url:	https://twitter.com/dirkfabisch
  #   desc: Follow me on twitter
  #   share_url: http://twitter.com/share
  #   share_title: ?text=
  #   share_link: "&amp;url="

  - icon:	facebook
    url:	https://www.facebook.com/komang.luce
    desc: Connect with me facebook
    share_url:
    share_title: 
    share_link: 

  - icon:	github
    url:	https://github.com/kopisusu
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
